### ISSUE TITLE
Como subi ou abir este projeto?

### ISSUE THREAD

**Issue by edivancarvalho** [karantes/REST-Spring#12]
Boa noite, eu não conseguir subi este projeto nem o intellijet e nem o eclipse, tem como por o passo a passo para subi este projeto?

Eu entrei no primeiro branch e tentei roda o projeto, mais infelimente não deu certo tentei a versao 1.8 do java e tambem a versao 17lts, como no arquivo de configuração deste projeto esta como 1.8 eu modifiquei na minha idea para o SDK 1.8.

Obrigado.

**Comment by jbai86** [comment]
OPa EdinCarvalho tive o mesmo erro também tentando seguir as aulas. 

Consegui ver nos logs que o erro geralmente acontece porque a aplicação tenta usar a porta 8080, e quando vê que tem outra aplicação por lá, ele para o servidor. 

Para conseguir rodar segui este passo: 

Vai na Pasta resources -> e no arquivo application.properties adiciona uma nova porta -> server.port=8081 
No caso utilizei a 8081

Só não esquece de fazer as requisições do EndPoint na nova porta, ok ? 

Exemplo: localhost:8081/produto/save

**Comment by edivancarvalho** [comment]
Bom dia, Obrigado.
